theme:
  active: 255,195,255
  banner: 255,195,255
  error_border: Red
  error_text: LightRed
  hint: Yellow
  hovered: Magenta
  inactive: 211,232,255
  playbar_background: Black
  playbar_progress: LightMagenta
  playbar_progress_text: Cyan
  playbar_text: 234,234,234
  selected: 178,88,219
  text: 211,232,255
  header: 234,234,234
