theme:
  active: 255,195,255
  banner: 255,195,255
  error_border: Red
  error_text: LightRed
  hint: Yellow
  hovered: Magenta
  inactive: 243,249,254
  playbar_background: Black
  playbar_progress: LightMagenta
  playbar_progress_text: Cyan
  playbar_text: 234,234,234
  selected: 178,88,219
  text: 243,249,254
  header: 234,234,234

keybindings:
  shuffle: "s"
  repeat: "r"
  jump_to_album: "a"
  jump_to_artist_album: "A"
  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "+"
  toggle_playback: " "
  seek_backwards: "<"
  seek_forwards: ">"
  next_track: "n"
  previous_track: "p"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  search: "/"
  audio_analysis: "v"
  jump_to_context: "o"
  basic_view: "B"
  add_item_to_queue: "z"
